2022-11-17 16:40:34 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: APIScopusCrawler)
2022-11-17 16:40:34 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.9.2 (default, Feb 28 2021, 17:03:44) - [GCC 10.2.1 20210110], pyOpenSSL 20.0.1 (OpenSSL 1.1.1n  15 Mar 2022), cryptography 3.3.2, Platform Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
2022-11-17 16:40:34 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'APIScopusCrawler',
 'LOG_FILE': 'logs/APIScopusCrawler/scopus_api/68626bd8667d11eda27174852a1dbaf2.log',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'APIScopusCrawler.spiders',
 'RETRY_TIMES': 10,
 'SPIDER_MODULES': ['APIScopusCrawler.spiders'],
 'URLLENGTH_LIMIT': 10000}
2022-11-17 16:40:34 [scrapy.extensions.telnet] INFO: Telnet Password: 8351c41b732a32b7
2022-11-17 16:40:35 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2022-11-17 16:40:38 [scrapy_fake_useragent.middleware] INFO: Using '<class 'scrapy_fake_useragent.providers.FakeUserAgentProvider'>' as the User-Agent provider
2022-11-17 16:40:38 [scrapy_fake_useragent.middleware] INFO: Using '<class 'scrapy_fake_useragent.providers.FakeUserAgentProvider'>' as the User-Agent provider
2022-11-17 16:40:38 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy_fake_useragent.middleware.RandomUserAgentMiddleware',
 'scrapy_fake_useragent.middleware.RetryUserAgentMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2022-11-17 16:40:38 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2022-11-17 16:40:39 [twisted] CRITICAL: Unhandled error in Deferred:
2022-11-17 16:40:39 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/python3/dist-packages/scrapy/crawler.py", line 87, in crawl
    self.engine = self._create_engine()
  File "/usr/lib/python3/dist-packages/scrapy/crawler.py", line 101, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "/usr/lib/python3/dist-packages/scrapy/core/engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "/usr/lib/python3/dist-packages/scrapy/core/scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "/usr/lib/python3/dist-packages/scrapy/middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/usr/lib/python3/dist-packages/scrapy/middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/usr/lib/python3/dist-packages/scrapy/utils/misc.py", line 173, in create_instance
    instance = objcls(*args, **kwargs)
  File "/home/denis/BIGDATA-SCOPUS/scopusCrawler/APIScopusCrawler/APIScopusCrawler/pipelines.py", line 20, in __init__
    self.connection = psycopg2.connect(host=self.hostname, user=self.username, password=self.password, dbname=self.database)
  File "/home/denis/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

